ManageRestaurant/WebApp/Controllers/TypeOfEmployeeController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class TypeOfEmployeeController : Controller
    {
        // GET: TypeOfEmployee
        TypeOfEmployeeDAL rsdal;

        public TypeOfEmployeeController()
        {
            rsdal = new TypeOfEmployeeDAL();
        }
        // GET: TypeOfEmployee
        public ActionResult Index()
        {
            List<TypeOfEmployeeBLL> list = rsdal.GetAllType();
            return View(list);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Add(TypeOfEmployeeBLL model)
        {
            if (ModelState.IsValid)
            {
                var ct = new TypeOfEmployeeBLL
                {
                    TypeID = model.TypeID,
                    NameOfType = model.NameOfType
                };

                //cbo.AddCategory(ct);
                rsdal.AddTypeOfEmployee(ct);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Update(int id)
        {
            TypeOfEmployeeBLL type = rsdal.GetTypeById(id);
            return View(type);
        }
        [HttpPost]
        public ActionResult Update(TypeOfEmployeeBLL e)
        {
            rsdal.UpdateTypeOfEmployee(e);
            return RedirectToAction("Index");
        }

    }
}

ManageRestaurant/WebApp/Views/TypeOfEmployee/Add.cshtml
@model DAL.TypeOfEmployeeBLL

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>AddCategory</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameOfType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameOfType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameOfType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ManageRestaurant/WebApp/Views/TypeOfEmployee/Index.cshtml
@model IEnumerable<DAL.TypeOfEmployeeBLL>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2 class="text-primary">Type Of Employee</h2>

<p>
    @*@Html.ActionLink("Create New", "Add", new { @class = "btn btn-primary"})*@
    <a href="@Url.Action("Add", "TypeOfEmployee")" class="btn btn-primary">Create New</a>
</p>
<table class="table table-bordered table-hover table-responsive" id="t">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameOfType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameOfType)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Update", new { id = item.TypeID }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts {
    $(function(){
    $('#t').DataTable();
    });
}

ManageRestaurant/WebApp/Views/TypeOfEmployee/Update.cshtml
@model DAL.TypeOfEmployeeBLL

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Update</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TypeOfEmployeeBLL</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TypeID)

        <div class="form-group">
            @Html.LabelFor(model => model.NameOfType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameOfType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameOfType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>